title: The Road to Somewhere
description: The Road to Somewhere — polished Streamer.bot extensions for creators.
baseurl: ""
url: "https://duhbuhhuh.xyz"
rts_services_url: "https://osiuynezqmocapioekoa.supabase.co"
include:
  - extensions
